version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "jameswspears-github-io"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1qqocxg5iwv2x"
s3_prefix = "jameswspears-github-io"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
disable_rollback = true
